# Generated by Django 3.2.17 on 2023-06-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='biography',
            new_name='country',
        ),
        migrations.AddField(
            model_name='artists',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
