# Generated by Django 3.2.17 on 2023-05-13 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist_name',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='artists',
            name='category',
        ),
    ]
