# Generated by Django 3.2.17 on 2023-05-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_auto_20230507_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Artists'},
        ),
    ]
