# Generated by Django 3.2.17 on 2023-05-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_identifier'),
        ('artists', '0002_auto_20230513_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
