# Generated by Django 3.2.17 on 2023-07-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_artists_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={},
        ),
    ]
