# Generated by Django 3.2.17 on 2023-07-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_biography'),
        ('artists', '0004_alter_artists_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
