# Generated by Django 3.2.17 on 2023-07-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artists_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='category',
            new_name='product_artist',
        ),
    ]
