# Generated by Django 3.2.17 on 2023-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
