# Generated by Django 3.2.17 on 2023-05-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='biography',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
