# Generated by Django 3.2.17 on 2023-07-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_rename_category_artists_product_artist'),
        ('products', '0007_category_biography'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductArtist',
        ),
        migrations.AlterModelOptions(
            name='productartist',
            options={'verbose_name_plural': 'ProductArtists'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='artist',
        ),
    ]
